src/app.module.ts, src/restaurants/restaurants.controller.ts, src/restaurants/restaurants.module.ts, src/restaurants/restaurants.service.ts
- restaurants 초기 파일 생성
- init_restaurants_file
- N
- N
- N
- N
- N
=> [INIT] restaurants 파일 초기 생성

.gitignore, package-lock.json, package.json, src/app.module.ts
- db 연동을 위해 app.module 수정
ex) feat_db_setting -> main
- `app.module.ts` TypeOrmModule 설정
- typeorm, mysql2, @nestjs/typeorm npm
- .env 파일 gitignore 처리
=> Feat db setting

.dockerignore, Dockerfile
- 배포 및 ci/cd를 위한 docker 설정
docs_docker_file -> main
- Dockerfile
- .dockerignore
=> [DOCS] 도커 설정

src/users/users.controller.ts
- controller login부분 return 형태 수정
- feat_user_login -> main
- #4
- `users.controller.ts`: return 형태 수정
- 
-
=> [REFACTOR] controller login부분 return 형태 수정

package-lock.json
- cd pipeline 오류로 npm 설정이 문제 인거 같아서 수정해주었다.
- 우선 package-lock이 문제인지 확인해 보고 계속 오류가 나면 다른 방법을 찾아야함
- feat_user_login -> main
- #4
- 
- 
-
=> [FIX] cd pipeline 오류로 npm 설정 수정해주었다.

src/restaurants/restaurants.module.ts, src/users/users.controller.ts, src/users/users.module.ts, src/users/users.service.ts
- isFirstLogin를 이용해서 첫번째 로그인 확인 로직 추가
- refactor_users_login -> main
- #4 
- `restaurants.module.ts`: exports부분에  RestaurantsModule 추가해 주었습니다. users.module.ts에서 사용해야해서
- users.controller.ts, users.service.ts, users.module.ts 에서 로직 수정
- 
-
=> [REFACTOR] 첫번째 로그인 확인 로직 추가

src/categories/categories.controller.ts, src/categories/categories.service.ts
-  카테고리 삭제 api 구현
- 
- feat_category_delete -> feat_category_put
- #16
- 
- 
- 수정과 마찬가지로 id 두개를 확인해서 삭제하는데 category id만 확인해도 되는지 확인 필요
=> [FEAT] 카테고리 삭제 api 구현

src/categories/categories.controller.ts, src/categories/categories.service.ts
- 카테고리 수정 api
- feat_category_get -> feat_category_put
- #16
- 
- 
- 현재 category 를 수정할때 category id와 restaurant_id를 둘다 확인해서 수정하고 있는데 카테고리 id만 확인해도 괜찮은 지 헷깔립니다.
=> [FEAT] 카테고리 수정 api

src/categories/categories.controller.ts, src/categories/categories.service.ts, src/categories/dtos/create-categories.dto.ts, src/categories/entities/categories.entity.ts
- 카테고리 추가 api 구현
- feat_category_post -> feat_category_get
- #16 
- 
- 
- 조회 부분 배열로 받도록 수정 해주었다.
=> [FEAT] 카테고리 추가 api 구현

src/menus/menus.controller.ts, src/menus/menus.service.ts
- 메뉴 삭제 api 구현
- feat_menu_delete -> feat_menu_put
- #17 
- 
- 
-
=> [FEAT] 메뉴 삭제 api 구현

src/menus/dtos/update-menus.dto.ts, src/menus/menus.controller.ts, src/menus/menus.service.ts
- 메뉴 수정 api : menu put 
- feat_menu_put -> feat_menu_add
- #17 
- 
- 
-
=> [FEAT] 메뉴 수정 api 구현

src/menus/dtos/create-menus.dto.ts, src/menus/dtos/update-menus.dto.ts, src/menus/menus.controller.ts, src/menus/menus.service.ts
- menu 추가 (post) : 메뉴 추가 api 구현
- feat_menu_add -> feat_menu_get-one
- #17 
- 
- 
-
=> [FEAT] 메뉴 추가 api 구현

src/menus/dtos/create-menus.dto.ts, src/menus/dtos/update-menus.dto.ts, src/menus/entities/menus.entity.ts, src/menus/menus.controller.ts, src/menus/menus.service.ts, src/options/entities/options.entity.ts
- menus (get) 메뉴 개별 조회 api 구현
- feat_menu_get-one -> feat_menu_get-all
- #17 
-
- 
-
=> [FAET] 메뉴 개별 조회 api 구현

src/categories/categories.controller.ts, src/categories/categories.service.ts, src/categories/dtos/create-categories.dto.ts, src/categories/dtos/update-categories.dto.ts, src/categories/entities/categories.entity.ts, src/menus/entities/menus.entity.ts
- 카테고리 제거 시 연결된 메뉴들도 삭제되도록 entity 작성
- UseGuards 추가
- 주석 정리
- refactor_category -> main
- #16 
- `menus.entity.ts`, `categories.entity.ts` : 연결 삭제 되도록 수정
- `categories.controller.ts` : UseGuards 추가
- 주석 추가
- 
-
=> [REFACTOR] category 정리 

src/options/dtos/create-options.dro.ts, src/options/dtos/update-options.dto.ts, src/options/options.controller.ts, src/options/options.service.ts
- 옵션 삭제 api 구현
- feat_option_delete -> feat_option_put
- #32 
- 
- 
-
=> [FEAT] 옵션 삭제 api 구현

src/options/dtos/update-options.dto.ts, src/options/options.controller.ts, src/options/options.service.ts
- 옵션 수정 api 구현
- feat_option_put -> feat_option_post
- #32 
- 
- 
-
=> [FEAT] 옵션 수정 api 구현

src/app.module.ts, src/menus/entities/menus.entity.ts, src/options/dtos/create-options.dro.ts, src/options/dtos/update-options.dto.ts, src/options/entities/options.entity.ts, src/options/options.controller.ts, src/options/options.module.ts, src/options/options.service.ts
- options post api : 옵션 추가 api 구현
- feat_option_post -> main
- #32 
- 
- 
- restaurant id 가 필요 없는 것 같은데 없애는게 맞는지 확인 필요하다
=> [FEAT] 옵션 추가 api 구현

src/categories/categories.service.ts, src/categories/dtos/create-categories.dto.ts, src/categories/dtos/update-categories.dto.ts
- category 프론트에서 받는값 이름 수정
- refactor_category
- #16 
- 
- 
-
=> [REFACTOR] category request body 값 이름 수정

src/menus/dtos/create-menus.dto.ts, src/menus/dtos/update-menus.dto.ts, src/menus/menus.controller.ts, src/menus/menus.service.ts
- 메뉴 dto 이름 수정
- 메뉴 수정 api 프론트로 받는 request body 이름 수정
- refactor_menu -> main
- #17 
- 
- 
-
=> [REFACTOR] menu

src/calls/calls.controller.ts, src/calls/calls.service.ts, src/calls/entities/calls.entity.ts
- 호출(calls) 삭제 api 구현
- feat_call_delete -> feat_call_put
- #40 
- 
- 
-
=> [FEAT] 호출(calls) 삭제 api 구현

src/calls/calls.controller.ts, src/calls/calls.service.ts
- 호출 조회 api 구현 calls get
- feat_call_get -> feat_call_post
- #40 
- 
- 
-
=> [FEAT] 모든 호출 조회 api구현

src/app.module.ts, src/calls/calls.controller.ts, src/calls/calls.module.ts, src/calls/calls.service.ts, src/calls/dtos/create-calls.dto.ts, src/calls/dtos/update-calls.dto.ts, src/calls/entities/calls.entity.ts
- 호출 추가 api 구현
- feat_call_post -> main
- #40 
- 
- 
-
=> [FEAT] 호출 추가 api 구현

src/main.ts
- enableCors 옵션 설정
- origin 옵션의 도메인은 환경변수로 설정
refactor_cors -> dev
=> [REFACTOR] cors 옵션 설정

src/auth/auth.module.ts, src/users/users.module.ts
- 로그인 오류 해결
- user 모듈에서 auth모듈 참조
- auth 모듈, user 모듈 서로 참조하므로 순환 의존성 해결
refactor_auth -> dev
=> [REFACTOR] auth 모듈 수정

src/main.ts
- 포트 넘버 환경변수 처리
refactor_port_env -> dev
=> [REFACTOR] 포트 넘버 환경변수 처리

src/calls/calls.module.ts, src/calls/calls.service.ts, src/calls/entities/calls.entity.ts, src/categories/categories.controller.ts, src/categories/categories.module.ts, src/categories/categories.service.ts, src/categories/entities/categories.entity.ts, src/menus/entities/menus.entity.ts, src/menus/menus.controller.ts, src/menus/menus.module.ts, src/menus/menus.service.ts, src/options/entities/options.entity.ts, src/options/options.module.ts, src/options/options.service.ts, src/orders/entities/orders.entity.ts, src/orders/orders.module.ts, src/orders/orders.service.ts, src/restaurants/entities/restaurants.entity.ts
- 레스토랑과 메뉴, 카테고리, 호출, 옵션에서 모든 관계 설정해줌
- 관계 설정으로 서비스 부분 수정
- refactor_restaurants_fk
- 
- 
- 
-
=> [REFACTOR] 레스토랑과 관계 설정된 부분 모두 수정

src/calls/calls.service.ts, src/calls/entities/calls.entity.ts, src/categories/entities/categories.entity.ts, src/menus/entities/menus.entity.ts, src/options/entities/options.entity.ts, src/options/options.service.ts, src/orders/orders.service.ts
- 프론트에서 받는 변수 면과 디비의 칼람 명이 달라 인식이 안되는 오류 수정(entity)
- entity 수정으로 생긴 오류 수정 service에서 변수명 수정해 주었다.
- fix_entity -> dev
- 
- 
- 
-
=> [FIX] entity 칼람 이름

src/main.ts
- cors allowedHeaders 옵션에 'Content-Type' 추가
refactor_cors -> main
=> [REFACTOR] cors 옵션

src/auth/jwt.strategy.ts, src/calls/calls.controller.ts, src/categories/categories.controller.ts, src/menus/menus.controller.ts, src/orders/orders.controller.ts, src/restaurantTables/restaurantTables.controller.ts, src/restaurants/restaurants.controller.ts, src/urls/urls.controller.ts, src/users/users.service.ts
- jwt로 레스토랑id, userid 데이터 사용하도록 수정
refactor_auth -> main
- 
- 
- 
-
=> [REFACTOR] jwt로 레스토랑id, userid 데이터 사용하도록 수정

src/calls/calls.controller.ts, src/categories/categories.controller.ts, src/menus/menus.controller.ts, src/options/options.controller.ts, src/orders/orders.controller.ts, src/restaurantTables/restaurantTables.controller.ts, src/restaurants/restaurants.controller.ts, src/urls/urls.controller.ts
- UseGuards 모든 컨트롤러에 적용
refactor_UseGuards -> main
=> [REFACTOR] UseGuards 컨트롤러 전체 적용

src/restaurantTables/entities/restaurantTables.entity.ts, src/restaurantTables/restaurantTables.controller.ts, src/restaurantTables/restaurantTables.service.ts, src/restaurants/dto/update-restaurants.dto.ts, src/users/users.service.ts
- 주석 정리
- response 데이터 카멜케이스로 변경
- 예외처리 정리 및 한글화
- 메소드 엔드포인트, 이름 수정
- restaurantTable 추가/삭제 시 restaurant.total_table_count에 연동
refactor_restaurantTables -> dev
- #55
=> [REFACTOR] restaurant tables api

src/restaurants/entities/restaurants.entity.ts
- 테스트중 오류가 나서 확인해보니 restaurant entity를 잘못 수정했음.
- 정상 작동하도록 entity 수정.
fix_execution -> dev
=> [FIX] restaurant entity

src/restaurants/dto/create-restaurants.dto.ts, src/restaurants/restaurants.service.ts
- request 데이터 카멜케이스로 변경
refactor_restaurants_request_case -> dev
- #55
=> [REFACTOR] restaurants request 데이터 카멜케이스로 변경

package-lock.json, package.json, src/app.module.ts, src/img-upload/imgUpload.controller.ts, src/img-upload/imgUpload.module.ts, src/img-upload/imgUpload.service.ts
- 이미지 s3에 업로드하는 api 구현
- feat_imgUpload -> dev
- #56 
- 
- s3 권한 오류 : 정책 수정 후 해결 
-
=> [FEAT] img upload api 구현

src/menus/dtos/create-menus.dto.ts, src/menus/dtos/get-all-menus-response.dto.ts, src/menus/dtos/get-menu-response.dto.ts, src/menus/dtos/update-menus.dto.ts, src/menus/entities/menus.entity.ts, src/menus/menus.controller.ts, src/menus/menus.service.ts
- 메뉴에 라벨 추가
- 메뉴 조회할때 없었던 categoryId 추가
- refactor_menus_labels-> dev
- ex) #57 
- 
- 
-
=> [REFACTOR] menus에 추가 labels 적용

src/orders/dto/create-orders.dto.ts, src/orders/dto/order-summary.dto.ts, src/orders/dto/order-table-summary.dto.ts, src/orders/entities/orders.entity.ts, src/orders/orders.controller.ts, src/orders/orders.gateway.ts, src/orders/orders.module.ts, src/orders/orders.service.ts, src/restaurantTables/entities/restaurantTables.entity.ts
- 주석 정리
- 예외처리 한글화
- restaurantTables 와의 FK 해제, table_num으로 수정
- orders와 options의 중간 db 테이블 생성
- request 및 response 카멜케이스로 변경
refactor_orders -> dev
- #55 
- 추후 response.dto 추가 필요해 보입니다.
=> [REFACTOR] orders API

src/app.module.ts, src/designs/designs.controller.ts, src/designs/designs.module.ts, src/designs/designs.service.ts, src/designs/dto/create-designs.dto.ts, src/designs/dto/update-designs.dto.ts, src/designs/entities/designs.entity.ts, src/restaurants/entities/restaurants.entity.ts, src/restaurants/restaurants.module.ts, src/restaurants/restaurants.service.ts
- designs api 구현
- 디자인 조회 메소드
- 디자인 수정 메소드
feat_designs_api -> dev
- #62 
- 현재 만들어진 디자인 api는 추후 '현재 적용된' 디자인을 관리하는 api로 고도화될 예정입니다.
- 추후 디자인 프리셋을 저장하는 db table과 api를 만들고, 해당 프리셋을 참조 or 복사해서 저장할 생각입니다.
- 위의 참고사항에 대해 프론트 팀원 분들과 상의가 필요합니다.
=> [FEAT] designs API

src/calls/entities/calls.entity.ts, src/categories/entities/categories.entity.ts, src/restaurants/dto/create-restaurants.dto.ts, src/restaurants/dto/update-restaurants.dto.ts, src/restaurants/entities/restaurants.entity.ts, src/restaurants/restaurants.module.ts, src/restaurants/restaurants.service.ts, src/users/entities/users.entity.ts, src/users/users.module.ts, src/users/users.service.ts
- 식당 update dto를 엔티티 참조에서 create dto 참조로 변경
- restaurants entity에서 참조되지 않고 있던 users.id 참조하도록 변경
- 위의 변경사항에 따른 service, module 파일 수정
fix_restaurants_update -> dev
- #55
=> [FIX] restaurants update

src/designPresets/entities/designPresets.entity.ts, src/designs/designs.controller.ts, src/designs/designs.module.ts, src/designs/designs.service.ts, src/designs/dto/create-designs.dto.ts, src/designs/entities/designs.entity.ts, src/restaurants/restaurants.module.ts, src/restaurants/restaurants.service.ts
- designs api의 목적을 '현재 적용된 디자인'을 저장하도록 변경
- 엔티티, dto 수정
- 기존 메소드 삭제 후 위의 변경사항에 맞는 메소드 생성
- 식당이 생성될때 만들어지는 '기본 디자인'이 바로 적용되도록 restaurants.service.ts파일 변경
refactor_designs -> dev
- #71
=> [REFACTOR] designs api

src/users/users.service.ts
=> [REFACTOR] users service 주석 제거

src/categories/categories.service.ts
- category service 주석 제거
- dev->main
=> [REFACTOR] category service 주석 제거

src/orders/orders.controller.ts, src/orders/orders.service.ts
- order 개별 삭제 메소드
- order 테이블 별 전체 삭제 메소드
feat_orders_delete -> dev
- #80
=> [FEAT] orders 개별 삭제, 테이블별 삭제 메소드

src/app.module.ts, src/auth/jwt.strategy.ts, src/customer-jwt/customer-jwt.controller.ts, src/customer-jwt/customer-jwt.module.ts, src/customer-jwt/customer-jwt.service.ts, src/users/users.service.ts
- 소비자 접근 시 jwt 발행 및 검증
- feat_customer_token -> dev
- #78 
- 
- 
- jwt 확인시 type으로 구분을 해서 필요한 jwt인지를 확인하는데 이 로직에 문제가 없는지 확인해 주세요!
=> [FEAT] 소비자 접근 시 jwt 발행 및 검증

src/auth/jwt.strategy.ts, src/customer-jwt/customer-jwt.module.ts
- customer 토큰 발급 오류 해결
- refactor_strategy -> dev
- #79 
-
=> [REFACTOR] customer 토큰 발급 오류 해결

src/designPresets/designPresets.controller.ts, src/designs/designs.controller.ts, src/orders/orders.controller.ts, src/restaurantTables/restaurantTables.controller.ts, src/restaurants/restaurants.controller.ts, src/urls/urls.controller.ts
- 관리자만 접근해야 하는 메소드에서 토큰 타입을 확인하고 실행되도록 변경
refactor_auth_type -> dev
=> [REFACTOR] 토큰 타입에 따른 메소드 별 검증

src/categories/categories.controller.ts, src/categories/categories.service.ts, src/categories/dtos/update-categories.dto.ts
- 소비자 접근 확인 로직 추가
- category 수정 api 제거 (사용 안되기 때문에)
- category  생성과 함께 id 반환해주도록 수정
- refactor_category -> dev
- ex) #31 
- 
- 
-
=> [REFACTOR] category 수정

src/calls/calls.controller.ts
- 호출부 소비자, 관리자 토큰 확인 로직 추가
- callId 변수명 수정
- refactor_call -> dev
=> [REFACTOR] call

src/menus/dtos/create-menus.dto.ts, src/menus/dtos/update-menus.dto.ts
- 메뉴  dto id uuid 로 수정
- refactor_menu -> dev
=> [REFACTOR] 메뉴  dto id uuid 로 수정

src/orders/orders.service.ts
- order가 없을때 에러 반환 -> order(빈 배열) 반환으로 변경
refactor_orders_get -> dev
- #93
=> [REFACTOR] orders의 get 메소드 2개 order가 없을때도 order 반환

src/menus/dtos/create-menus.dto.ts, src/menus/dtos/update-menus.dto.ts, src/menus/entities/menus.entity.ts
- menu img 길이 수정
- refactor_menu -> dev
=> [REFACTOR]: menu img 길이 수정

src/orders/orders.controller.ts, src/orders/orders.service.ts
- 메소드 명 변경
- 단일 order 추가 -> 여러 order를 추가 로 변경
- response 제거
refactor_orders_create -> dev
- #99
=> [REFACTOR] createOrder가 여러 order를 입력받을 수 있게 변경

src/designPresets/dto/create-designPresets.dto.ts, src/designPresets/entities/designPresets.entity.ts
- entity에 design_iamge 추가
- create dto에 design_image 추가
refactor_designPresets_entity -> dev
- #101
=> [REFACTOR] design presets entity에 design_image 추가

src/categories/categories.service.ts, src/customer-jwt/customer-jwt.controller.ts, src/menus/dtos/create-menus.dto.ts, src/menus/dtos/update-menus.dto.ts, src/menus/menus.service.ts, src/options/dtos/option-response.dto.ts, src/options/options.controller.ts, src/options/options.service.ts, tsconfig.json
- respones 형태 수정
- menu 정렬
- category 정렬
- option 데이터 3개로 줄임
- refactor_response -> dev
=> [REFACTOR] response 형태 수정

src/socket/socket.gateway.ts
- socket server 부분 수정(사용 안되어서 생긴 경고)
-  refactor_socket ->dev
=> [REFACTOR] socket server 부분 수정

src/socket/socket.gateway.ts
- 소켓 cors 설정 추가
- refactor_socket -> dev
=> [REFACTOR] 소켓 cors 설정 추가

src/orders/orders.service.ts
- orders의 GET 메소드들의 response에 category와 categoryName 추가
refactor_orders_get
=> [REFACTOR] 조회 메소드 reponse에 category, categoryName 추가

src/orders/orders.service.ts
- createOrders 안쓰는 변수 제거
chore_orders -> dev
=> [CHORE] 안쓰는 변수 제거

src/orders/orders.controller.ts, src/orders/orders.service.ts, src/socket/socket.gateway.ts
- socket order 부분 추가
- refactor_socket -> dev
=> [REFACTOR]  socket order 부분 추가

src/designs/designs.controller.ts, src/orders/orders.controller.ts, src/orders/orders.service.ts, src/socket/socket.gateway.ts
- socket order 반환 수정
- 필요없는 import 제거
- refactor_socket -> dev
=> [REFACTOR] socket 수정

src/designs/designs.controller.ts, src/orders/orders.controller.ts, src/orders/orders.service.ts, src/socket/socket.gateway.ts
=> 4.4차 스프린트 적용

src/restaurants/restaurants.service.ts
- 식당 생성시 기본적으로 제공되는 색 코드 작성
refactor_default_designPreset
=> [REFACTOR] 기본 디자인 색 설정

src/users/users.controller.ts, src/users/users.service.ts
- 관리자 jwt 재발급 api
- feat_jwt_reissue -> dev
=> [FEAT] 관리자 jwt 재발급 api
